import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const fontsDir = path.join(rootDir, "docs/dashboard/fonts");
const targetTsFile = path.join(rootDir, "src/dashboard-fonts.ts");

function toBase64(filename) {
  const filePath = path.join(fontsDir, filename);
  const buffer = fs.readFileSync(filePath);
  return buffer.toString("base64");
}

const bsd700Base64 = toBase64("big-shoulders-display-latin-700-normal.woff2");
const bsd800Base64 = toBase64("big-shoulders-display-latin-800-normal.woff2");
const jbm400Base64 = toBase64("jetbrains-mono-latin-400-normal.woff2");
const jbm500Base64 = toBase64("jetbrains-mono-latin-500-normal.woff2");

const tsContent = `// Auto-generated by scripts/dashboard-fonts.mjs — DO NOT EDIT DIRECTLY

export const BIG_SHOULDERS_700_BASE64 = "${bsd700Base64}";
export const BIG_SHOULDERS_800_BASE64 = "${bsd800Base64}";
export const JETBRAINS_MONO_400_BASE64 = "${jbm400Base64}";
export const JETBRAINS_MONO_500_BASE64 = "${jbm500Base64}";

export const DISPLAY_FONT_STACK = "'Big Shoulders Display', \\"Bahnschrift\\", \\"Arial Narrow\\", Impact, sans-serif";
export const MONO_FONT_STACK = "'JetBrains Mono', ui-monospace, \\"Cascadia Code\\", Consolas, monospace";

export const FONT_FACES_CSS = \`
@font-face {
  font-family: 'Big Shoulders Display';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('data:font/woff2;base64,\${BIG_SHOULDERS_700_BASE64}') format('woff2');
}
@font-face {
  font-family: 'Big Shoulders Display';
  font-style: normal;
  font-weight: 800;
  font-display: swap;
  src: url('data:font/woff2;base64,\${BIG_SHOULDERS_800_BASE64}') format('woff2');
}
@font-face {
  font-family: 'JetBrains Mono';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('data:font/woff2;base64,\${JETBRAINS_MONO_400_BASE64}') format('woff2');
}
@font-face {
  font-family: 'JetBrains Mono';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url('data:font/woff2;base64,\${JETBRAINS_MONO_500_BASE64}') format('woff2');
}
\`.trim();
`;

fs.writeFileSync(targetTsFile, tsContent, "utf8");
console.log(`Generated ${targetTsFile} successfully (${tsContent.length} bytes).`);
